FROM node:alpine
RUN uname -a
RUN echo $DATABASE_URL

# Create app directory
WORKDIR /app

# Install prisma for the migration
RUN npm install -g prisma --unsafe-perm

# Copy schema and migration folder
COPY ./prisma ./prisma/

CMD [ "prisma", "migrate", "dev"]