version: "3.9"

services:
  db:
    image: postgres:14.3-alpine
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

  web:
    stdin_open: true
    restart: unless-stopped

    depends_on:
      - db

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/app/src

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env.docker

volumes:
  postgres-data:
