version: "3.9"
services:
  db:
    image: postgres:14.3-alpine
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 5
      start_period: 2s

  web:
    stdin_open: true
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/app/src

    ports:
      - "${PORT}:${PORT}"

    env_file:
      - .env.docker

    command: sh -c "npx prisma migrate dev && npm run dev"

volumes:
  postgres-data:
