version: "3.9"
services:
  db:
    container_name: pg_container
    hostname: postgres
    image: postgres:latest
    restart: unless-stopped

    volumes:
      - postgres-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    ports:
      - "5432:5432"
  web:
    stdin_open: true
    container_name: web_container
    restart: unless-stopped

    depends_on:
      - db

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./src:/app/src

    ports:
      - "3333:3333"

    env_file:
      - .env

volumes:
  postgres-data:
